name: Deploy ADK Agent API to Cloud Run

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  PROJECT_ID: geni-project
  REGION: asia-south1
  SERVICE_NAME: adk-agent-api

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Decode service account key
      run: echo "${{ secrets.GCP_SA_KEY }}" | base64 -d > "${{ github.workspace }}/gcp-key.json"

    - name: Activate service account
      run: |
        gcloud auth activate-service-account --key-file="${{ github.workspace }}/gcp-key.json"

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: ${{ env.PROJECT_ID }}
        service_account_key: ${{ github.workspace }}/gcp-key.json
        export_default_credentials: true

    - name: Authenticate Docker to Google Cloud
      run: gcloud auth configure-docker

    - name: Build and push container to Artifact Registry
      run: |
        gcloud builds submit --tag gcr.io/${{ env.PROJECT_ID }}/${{ env.SERVICE_NAME }}

    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy ${{ env.SERVICE_NAME }} \
          --image gcr.io/${{ env.PROJECT_ID }}/${{ env.SERVICE_NAME }} \
          --region ${{ env.REGION }} \
          --platform managed \
          --allow-unauthenticated
