name: ADK Agent Engine Automation

on:
  workflow_dispatch:
    inputs:
      action:
        description: 'Choose action: deploy, list, delete'
        required: true
        default: 'deploy'
        type: choice
        options:
          - deploy
          - list
          - delete
      resource_name:
        description: 'Full resource name (only required for delete)'
        required: false

env:
  PYTHON_VERSION: '3.12'
  REGION: 'us-central1'
  MODEL: 'gemini-2.0-flash-exp'
  APP_NAME: 'Transcript Summarizer'
  REQUIREMENTS_FILE: 'requirements.txt'

jobs:
  adk_agent_workflow:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r ${{ env.REQUIREMENTS_FILE }}
        pip install google-adk==1.1.1 fire python-dotenv

    - name: Authenticate with Google Cloud
      uses: google-github-actions/auth@v2
      with:
        credentials_json: '${{ secrets.GCP_SA_KEY }}'

    - name: Set Google Cloud Project
      run: |
        echo "GOOGLE_CLOUD_PROJECT=${{ secrets.GCP_PROJECT_ID }}" >> .env
        echo "GOOGLE_CLOUD_LOCATION=${{ env.REGION }}" >> .env
        echo "GOOGLE_GENAI_USE_VERTEXAI=TRUE" >> .env
        echo "MODEL=${{ env.MODEL }}" >> .env
        echo "APP_NAME=\"${{ env.APP_NAME }}\"" >> .env

    - name: Deploy Agent
      if: ${{ github.event.inputs.action == 'deploy' }}
      run: |
        python3 transcript_summarization_agent/deploy_to_agent_engine.py

    - name: List Agents
      if: ${{ github.event.inputs.action == 'list' }}
      run: |
        python3 transcript_summarization_agent/agent_engine_utils.py list

    - name: Delete Agent
      if: ${{ github.event.inputs.action == 'delete' && github.event.inputs.resource_name != '' }}
      run: |
        python3 transcript_summarization_agent/agent_engine_utils.py delete "${{ github.event.inputs.resource_name }}"